### PR TITLE
Update zero-epwing-go to point to themoeway.

### PR DESCRIPTION
**Pull request by xythh**
Change package name to reflect new Yomitan location and update mod file to match.

### CODE REVIEW

**Review by Aquafina-water-bottle — APPROVED** [review]

**Review by djahandarie — CHANGES_REQUESTED** [review]
I'm confused about the PR name as well as the description of the second commit. Both commits replace `foosoft.net/projects/zero-epwing-go` with `github.com/themoeway/zero-epwing-go`, and I see no mention of yomichan/yomitan at all.

**Comment by xythh** [comment]
That's my bad on the commit message, https://github.com/themoeway/zero-epwing-go/pull/2/commits/1284b708b13880b420f1c452f9cec2230c5d71ea just changes the package directory to the one hosted on themoeway organiziation.

**Comment by djahandarie** [comment]
> That's my bad on the commit message, [1284b70](https://github.com/themoeway/zero-epwing-go/commit/1284b708b13880b420f1c452f9cec2230c5d71ea) just changes the package directory to the one hosted on themoeway organiziation.

I'd like to keep the git history on the main branch as clean as possible, so a couple options:
* fix the msg using `git commit --amend && git push -f`
* combine the two commits into one commit using `git reset --soft HEAD~2 &&
git commit && git push -f`
* squash merge the PR using the GitHub UI and fix the message then

Let me know what you prefer.

**Comment by xythh** [comment]
Combined both commits into a commit with a better message.

**Review by djahandarie — APPROVED** [review]

**Pull request merged**
